### ISSUE TITLE
Restart after update just closes the app on Windows

### ISSUE THREAD

**Issue by antelle** [antelle/keeweb#36]
How to fix this? There should be a better way.
https://github.com/atom/electron/issues/539

**Comment by antelle** [comment]
Fixed by soft unloading app main module and removing it from node.js module cache.

**Comment by Sigmanor** [comment]
I noticed that this bug is still present, when "Minimize app instead of close" is checked. After pressing "Restart to update" app just minimized to tray.

**Comment by antelle** [comment]
Thanks, will be fixed. It should of course be closed in this case, not minimized.
